---
title : 관계의 시각화
output:
  officedown::rdocx_document:
    reference_docx: bookdown.docx
    plots:
      style: Normal
      align: center
      fig.lp: 'fig:'
      topcaption: false
      caption:
        style: Image Caption
        pre: 'Figure '
        sep: ': '
        tnd: 0
        tns: '-'
        fp_text: !expr officer::fp_text_lite(bold = TRUE)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, out.width = '100%', dpi = 120, fig.width = 6.5)

library(showtext)
showtext_auto()
library(tidyverse)
library(readxl)
library(scales)
library(patchwork)

df_입학자 <- read_excel('c:/R/git/datavisualization/chap3/2021_연도별 입학자수.xlsx', 
                 ## 'data' 시트의 데이터를 불러오는데,
                 sheet = 'Sheet0',
                 ## 앞의 10행을 제외하고
                 skip = 3, 
                 ## 첫번째 행은 열 이름을 설정
                 col_names = FALSE, 
                 ## 열의 타입을 설정, 처음 8개는 문자형으로 다음 56개는 수치형으로 설정
                 col_types = c(rep('text', 2), rep('numeric', 30)))
df_입학자 <- df_입학자 |> select(1, 2, 5, 7, 9, 11, 13, 19, 29, 31)

## df_입학자의 열이름을 적절한 이름으로 설정
colnames(df_입학자) <- c('연도', '지역', '전문대학', '교육대학', '일반대학', '방송통신대학', '산업대학', '원격및사이버대학', '석사', '박사')

df_입학자 <- df_입학자 |> filter(!is.na(지역))

df_입학자_long <- df_입학자 |> pivot_longer(3:10, names_to = '학교종류', values_to = '입학생수')


```

```{r include=FALSE}

df_취업통계 <- read_excel('c:/R/git/datavisualization/chap3/2020년 학과별 고등교육기관 취업통계.xlsx', 
                     ## '학과별' 시트의 데이터를 불러오는데,
                     sheet = '학과별',
                     ## 앞의 13행을 제외하고
                     skip = 13, 
                     ## 첫번째 행은 열 이름으로 설정
                     col_names = TRUE, 
                     ## 열의 타입을 설정, 처음 9개는 문자형으로 다음 79개는 수치형으로 설정
                     col_types = c(rep('text', 9), rep('numeric', 79)))

## df_취업통계에서 첫번째부터 9번째까지의 열과 '계'로 끝나는 열을 선택하여 다시 df_취업통계에 저장
df_취업통계 <- df_취업통계 |> select(1:9, ends_with('계'), '입대자')

## df_취업통계 정보 확인
str(df_취업통계)
```

# 스캐터 플롯(Scatter Plot)

```{r}
set.seed(123)
df_취업통계_sample <- df_취업통계 |> filter(취업률_계 != 100, 졸업자_계 >= 1) |>
  filter(졸업자_계 < 500) |>
  sample_n(2000)
```

## 추세선 스캐터 플롯(scatter plot)

```{r}
p_scatter <- df_취업통계_sample |> 
  ggplot()

p_scatter1 <- p_scatter +
  geom_point(aes(x = 졸업자_계, y = 취업자_합계_계)) + 
  labs(title = '산점도', x = '졸업자수', y = '취업자수')

p_scatter1
```


```{r}
p_scatter2 <- p_scatter1 +
  geom_point(aes(x = 졸업자_계, y = 취업자_합계_계, color = 대계열)) + 
  labs(color = '계열구분')

p_scatter2
```


```{r}
p_scatter2 + 
  geom_smooth(aes(x = 졸업자_계, y = 취업자_합계_계, color = 대계열))
```

## 러그 스캐터 플롯(scatter plot)


```{r}
if(!require('ggrepel')) {
  install.packages('ggrepel')
  library(ggrepel)
}


p_scatter3 <- p_scatter2 + 
  geom_rug(aes(x = 졸업자_계, y = 취업자_합계_계), col= "steelblue", alpha=0.5)

p_scatter3
```

## 데이터 강조

```{r}
p_scatter4 <- p_scatter3 + 
  geom_point(data = df_취업통계_sample |> filter(학과명 == '컴퓨터정보학과'), aes(x = 졸업자_계, y = 취업자_합계_계), color = 'black', size = 2)

p_scatter4

```

```{r}
p_scatter5 <- p_scatter4 +
  ggrepel::geom_text_repel(data = df_취업통계_sample |> filter(학과명 == '컴퓨터정보학과'), aes(x = 졸업자_계, y = 취업자_합계_계, label = 학제))

p_scatter5
```

## encircle 스캐터 플롯(scatter plot)


```{r}
if(!require('ggalt')) {
  install.packages('ggalt')
  library(ggalt)
}

p_scatter6 <- p_scatter5 +
    geom_encircle(data = df_취업통계_sample |> filter(학과명 == '컴퓨터정보학과'), aes(x = 졸업자_계, y = 취업자_합계_계), color="darkred", size = 2)

p_scatter6
```

# 버블 차트(Bubble Chart)

```{r}
p_bubble <- df_취업통계_sample |> filter(대계열 == '인문계열') |> 
  ggplot()

p_bubble +
  geom_point(aes(x = 졸업자_계, y = 취업자_합계_계, size = 취업률_계, color = 취업률_계)) + 
  labs(title = '버블 차트', x = '졸업자수', y = '취업자수', color = '취업률', size = '취업률') 
  

```

# 상관도

```{r}
if(!require('ggcorrplot')) {
  install.packages('ggcorrplot')
  library(ggcorrplot)
}

corr <- round(cor(df_취업통계_sample[, 13:19]), 1)

ggcorrplot(corr, type = "lower", 
           lab = TRUE, 
           lab_size = 3, 
           method="square", 
           colors = c("tomato1", "white", "skyblue1"), 
           title="취업 상세 정보의 상관도", 
           ggtheme=theme_bw)
```

# 히트맵

```{r}
df_입학자_long |> filter(지역 != '전체') |> filter(학교종류 == '일반대학') |>
  ggplot() +
  geom_tile(aes(x = 연도, y = 지역, fill = 입학생수)) + 
  scale_fill_continuous(type = "viridis")
```



# geom_hex

```{r}
df_입학자_long |> filter(지역 != '전체') |> filter(학교종류 == '일반대학') |>
  ggplot() +
  geom_hex(aes(x = 연도, y = 지역)) + 
  scale_fill_continuous(type = "viridis")
```
