---
title : 데이터 시각화를 위한 plotly
output: 
  officedown::rdocx_document:
    reference_docx: bookdown.docx
    plots:
      style: Normal
      align: center
      fig.lp: 'fig:'
      topcaption: false
      fig_caption: yes
      caption:
        style: Image Caption
        pre: '실행결과 3- '
        sep: '.'
        tnd: 0
        tns: '-'
        fp_text: !expr officer::fp_text_lite(bold = TRUE)
      Normal: ['First Paragraph']
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, out.width = '100%', dpi = 120, fig.width = 6.5, fig.cap = TRUE)

```



```{r}
library(plotly)
library(readxl)
library(tidyverse)
df_입학자_r <- read_excel('2021_연도별 입학자수.xlsx', 
                 ## 'data' 시트의 데이터를 불러오는데,
                 sheet = 'Sheet0',
                 ## 앞의 10행을 제외하고
                 skip = 3, 
                 ## 첫번째 행은 열 이름을 설정
                 col_names = FALSE, 
                 ## 열의 타입을 설정, 처음 8개는 문자형으로 다음 56개는 수치형으로 설정
                 col_types = c(rep('text', 2), rep('numeric', 30)))

df_입학자_r <- df_입학자_r |> select(1, 2, 5, 7, 9, 11, 13, 19, 29, 31)

## df_입학자의 열이름을 적절한 이름으로 설정
colnames(df_입학자_r) <- c('연도', '지역', '전문대학', '교육대학', '일반대학', '방송통신대학', '산업대학', '원격및사이버대학', '석사', '박사')

df_입학자_r <- df_입학자_r |> filter(!is.na(지역))

df_입학자_long_r <- df_입학자_r |> pivot_longer(3:10, names_to = '학교종류', values_to = '입학생수')

```



```{python}
import pandas as pd
from dfply import *
import plotly.express as px
import plotly.graph_objects as go

df_입학생_p = pd.read_excel('C:/R/git/datavisualization/chap3/2021_연도별_입학자수.xlsx', sheet_name='Sheet0', header=(1, 2), nrows=400)
df_입학생_p = df_입학생_p >> select(0, 1, 2, 4, 8, 28, 30)
df_입학생_p.columns = ['연도', '시도', '전체', '전문대', '일반대', '석사', '박사']

fig = px.line(x=["a","b","c"], y=[1,3,2], title="sample figure")
print(fig)


list_연도 = df_입학생_p.loc[df_입학생_p['시도'] == '전체' , '연도']

list_일반대 = df_입학생_p.loc[df_입학생_p['시도'] == '전체' , '일반대']

list_전문대 = df_입학생_p.loc[df_입학생_p['시도'] == '전체' , '전문대']

list_석사 = df_입학생_p.loc[df_입학생_p['시도'] == '전체' , '석사']

list_박사 = df_입학생_p.loc[df_입학생_p['시도'] == '전체' , '박사']


fig = pe.line(x = list_연도, y = list_일반대)

fig.show()


fig1 = go.Figure()
fig1.add_trace(go.Scatter(x = list_연도, y = list_일반대, mode='lines+markers', name = '일반대'))
fig1.add_trace(go.Scatter(x = list_연도, y = list_전문대, mode='lines+markers', name = '전문대'))
fig1.add_trace(go.Scatter(x = list_연도, y = list_석사, mode='lines+markers', name = '석사'))
fig1.add_trace(go.Scatter(x = list_연도, y = list_박사, mode='lines+markers', name = '박사'))
fig1.show()


# import seaborn as sns
# import matplotlib.pyplot as plt
# import matplotlib.font_manager as fm
font_list = [font.name for font in fm.fontManager.ttflist]
font_list

df_입학생.head()
df_입학생.info()
df_입학생.describe()
df_입학생.loc[1:5]
df_입학생.shape[0]

df_입학생.index

df_입학생_전체 = df_입학생 >> filter_by(X.시도 == '전체')
df_입학생_전체.info()
plt.rcParams['axes.unicode_minus'] = False
plt.rcParams['font.family'] = 'Malgun Gothic'
sns.lineplot(x='연도', y='전체', data=df_입학생_전체)
plt.show()

```