---
title : 추세(trend)의 시각화
output:
  officedown::rdocx_document:
    reference_docx: bookdown.docx
    plots:
      style: Normal
      align: center
      fig.lp: 'fig:'
      topcaption: false
      caption:
        style: Image Caption
        pre: 'Figure '
        sep: ': '
        tnd: 0
        tns: '-'
        fp_text: !expr officer::fp_text_lite(bold = TRUE)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, out.width = '100%', dpi = 120, fig.width = 6.5)

library(showtext)
showtext_auto()
library(tidyverse)
library(readxl)
library(scales)
library(patchwork)

df_입학자 <- read_excel('c:/R/git/datavisualization/chap3/2021_연도별 입학자수.xlsx', 
                 ## 'data' 시트의 데이터를 불러오는데,
                 sheet = 'Sheet0',
                 ## 앞의 10행을 제외하고
                 skip = 3, 
                 ## 첫번째 행은 열 이름을 설정
                 col_names = FALSE, 
                 ## 열의 타입을 설정, 처음 8개는 문자형으로 다음 56개는 수치형으로 설정
                 col_types = c(rep('text', 2), rep('numeric', 30)))
df_입학자 <- df_입학자 |> select(1, 2, 5, 7, 9, 11, 13, 19, 29, 31)

## df_입학자의 열이름을 적절한 이름으로 설정
colnames(df_입학자) <- c('연도', '지역', '전문대학', '교육대학', '일반대학', '방송통신대학', '산업대학', '원격및사이버대학', '석사', '박사')

df_입학자 <- df_입학자 |> filter(!is.na(지역))

df_입학자_long <- df_입학자 |> pivot_longer(3:10, names_to = '학교종류', values_to = '입학생수')


```

```{r include=FALSE}

df_취업통계 <- read_excel('c:/R/git/datavisualization/chap3/2020년 학과별 고등교육기관 취업통계.xlsx', 
                     ## '학과별' 시트의 데이터를 불러오는데,
                     sheet = '학과별',
                     ## 앞의 13행을 제외하고
                     skip = 13, 
                     ## 첫번째 행은 열 이름으로 설정
                     col_names = TRUE, 
                     ## 열의 타입을 설정, 처음 9개는 문자형으로 다음 79개는 수치형으로 설정
                     col_types = c(rep('text', 9), rep('numeric', 79)))

## df_취업통계에서 첫번째부터 9번째까지의 열과 '계'로 끝나는 열을 선택하여 다시 df_취업통계에 저장
df_취업통계 <- df_취업통계 |> select(1:9, ends_with('계'), '입대자')

## df_취업통계 정보 확인
str(df_취업통계)

set.seed(123)
df_취업통계_sample <- df_취업통계 |> filter(취업률_계 != 100, 졸업자_계 >= 1) |>
  filter(졸업자_계 < 500) |>
  sample_n(2000)

df_취업통계_sample$과정구분 <- fct_relevel(df_취업통계_sample$과정구분, '전문대학과정', '대학과정', '대학원과정')

## 대계열의 순서를 맞추기 위해 과정구분을 팩터로 설정하고 레벨의 순서를 설정
df_취업통계_sample$대계열 <- fct_relevel(df_취업통계_sample$대계열, '인문계열', '사회계열', '교육계열', '자연계열', '공학계열', '의약계열', '예체능계열')

theme_set(theme(
    axis.ticks = element_blank(),
    axis.line = element_line(colour = "grey50"),
    panel.grid = element_line(color = "#b4aea9"),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_line(linetype = "dashed"),
    panel.background = element_rect(fill = "#fbf9f4", color = "#fbf9f4"),
    plot.background = element_rect(fill = "#fbf9f4", color = "#fbf9f4"), 
    legend.background = element_rect(fill = "#fbf9f4", color = "#fbf9f4"), 
    legend.key = element_rect(fill = "#fbf9f4", color = NA)
  ))
```

# 선 그래프

## 기본 그래프

```{r}
df_입학자_long$연도 <- lubridate::ymd(as.Date(df_입학자_long$연도, '%Y'))

df_입학자_long$학교종류 <- fct_relevel(df_입학자_long$학교종류, '전문대학', '일반대학', '교육대학', '산업대학',  '방송통신대학', '원격및사이버대학', '석사', '박사')


p_line <- df_입학자_long |> filter(지역 == '전체', 학교종류 %in% c('전문대학', '일반대학', '교육대학', '산업대학', '석사', '박사')) |>
  ggplot(aes(x = 연도, y = (입학생수)/1000)) + 
  scale_x_date(date_breaks = "2 years", date_labels = '%y') +
  labs(title = '선 그래프', x = '연도', y = '입학생수(천명)')

p_line +
  geom_line(aes(group = 학교종류, color = 학교종류))

```

### 스캐터 플롯과 병합

```{r}
p_mix_scatter <- p_line +
  geom_line(aes(group = 학교종류, color = 학교종류)) +
  geom_point(aes(color = 학교종류))

p_mix_scatter
```

```{r}
p_mix_scatter +
  geom_text(aes(color = 학교종류, label = scales::comma(입학생수, accuracy = 1)), size = 2, vjust = -1.5)

```

```{r}
p_mix_scatter1 <- p_mix_scatter +
  geom_text(data = df_입학자_long |> filter(지역 == '전체', 학교종류 %in% c('전문대학', '일반대학', '교육대학', '산업대학', '석사', '박사'), lubridate::year(연도) == '2021'),
            aes(color = 학교종류, label = scales::comma(입학생수, accuracy = 1)), 
            size = 3, vjust = -1.5, show.legend = FALSE)

p_mix_scatter1  
```

## 추세 선 그래프

```{r}
p_mix_scatter1 +
  geom_smooth(aes(group = 학교종류, color = 학교종류))
  
```

## 스파게티 선 그래프

### 분할(facet) 사용

```{r}
p_line +
  geom_line(aes(group = 학교종류)) +
  facet_wrap(~ 학교종류)

```



```{r}
p_line +
  geom_line(aes(group = 학교종류)) +
  facet_wrap(~ 학교종류, scales = 'free_y') + 
  geom_smooth(aes(group = 학교종류))

```


### 특정 범주만 강조

```{r}
p_line +
  geom_line(aes(group = 학교종류), color = 'grey75') + 
  geom_line(data = df_입학자_long |> filter(지역 == '전체', 학교종류 %in% c('전문대학')), aes(group = 1), color = 'darkred')
```


### 분할(facet)과 특정 범주 강조

```{r}
p_line +
  geom_line(aes(group = 학교종류), color = 'grey75') + 
  geom_line(data = df_입학자_long |> filter(지역 == '전체', 학교종류 %in% c('전문대학')), aes(group = 1), color = 'darkred') +
  facet_wrap(~ 학교종류)

```
## 축 다루기

### 이중 축 선 그래프

```{r}
p_dual_axis <- df_입학자_long |> filter(지역 == '전체', 학교종류 %in% c('일반대학', '석사', '박사')) |>
  ggplot(aes(x = 연도, y = (입학생수)/1000)) + 
  scale_x_date(date_breaks = "2 years", date_labels = '%y') +
  labs(title = '이중축 선 그래프', x = '연도', y = '입학생수(천명)')

p_dual_axis +
  geom_line(aes(group = 학교종류, color = 학교종류))

```

```{r}
first_max <- df_입학자_long |>
  filter(지역 == '전체', 학교종류 %in% c('일반대학')) |>
  summarise(max = max(입학생수)) |>
  pull()

second_max <- df_입학자_long |>
  filter(지역 == '전체', 학교종류 %in% c('석사')) |>
  summarise(max = max(입학생수)) |>
  pull()

ratio <- first_max/second_max

p_dual_axis1 <- p_dual_axis +
  geom_line(data = df_입학자_long |> filter(지역 == '전체', 학교종류 %in% c('일반대학')), aes(x = 연도, y = 입학생수 / 1000, group = 1, color = 학교종류)) +
  geom_line(data = df_입학자_long |> filter(지역 == '전체', 학교종류 %in% c('석사')), aes(x = 연도, y = (입학생수 * ratio) / 1000, group = 학교종류, color = 학교종류))

p_dual_axis1
```

```{r}
p_dual_axis2 <-p_dual_axis1 +
  scale_color_manual(values = c('일반대학' = 'darkred', '석사' = 'darkgreen'))

p_dual_axis2

```


```{r}
p_dual_axis3 <- p_dual_axis2 +
  scale_y_continuous(name = "일반대학 입학생수(천명)",  ## 첫번째 Y축 이름 설정
                     labels = scales::comma, 
                     sec.axis = sec_axis(trans=~ ./ratio, ## 두번째 Y축 변환식과 이름 설정
                                         name="석사 입학생수(천명)", 
                                         labels = scales::comma) 
    ) 

p_dual_axis3

```



```{r}
p_dual_axis3 +
  theme(legend.position = 'bottom', 
        axis.line.y.left = element_line(color = 'darkgreen'), 
        axis.text.y.left = element_text(color = 'darkgreen'), 
        axis.title.y.left = element_text(color = 'darkgreen'),
        panel.grid.major.y = element_line(color = 'darkgreen'), 
        axis.line.y.right = element_line(color = 'darkred'), 
        axis.text.y.right = element_text(color = 'darkred'), 
        axis.title.y.right = element_text(color = 'darkred')
        ) + 
  geom_hline(aes(yintercept = 90 * ratio), color = 'darkred', linetype = 2) + 
  geom_hline(aes(yintercept = 100 * ratio), color = 'darkred', linetype = 2)

```

### 축 자르기

```{r}
p_cut_axis <- df_입학자_long |> filter(지역 == '전체', 학교종류 %in% c('일반대학', '석사')) |>
  ggplot(aes(x = 연도, y = (입학생수)/1000)) + 
  geom_line(aes(group = 학교종류, color = 학교종류)) +
  scale_x_date(date_breaks = "2 years", date_labels = '%y') +
  labs(title = '선 그래프- 축 자르기', x = '연도', y = '입학생수(천명)')

p_cut_axis

```

```{r}
if(!require(ggbreak)) {
  install.packages('ggbreaks')
  library(ggbreak)
}

p_cut_axis + 
  scale_y_break(c(110, 310)) + 
  theme(axis.title.y = element_text(angle = 90))

```

# 슬로프 그래프

```{r}
df_입학자_long |> filter(지역 == '전체', lubridate::year(연도) %in% c(seq(from = 2001, to = 2021, by = 5)),  학교종류 %in% c('전문대학', '일반대학')) |>
  ggplot(aes(x = 연도, y = (입학생수)/1000)) + 
  geom_line(aes(group = 학교종류, color = 학교종류)) + 
  geom_label(aes(group = 학교종류, label = paste0(round(입학생수/1000, 0), '천')), label.size = NA, size = 3, fill = '#fbf9f4') + 
  scale_x_date(breaks = as.Date(as.character(seq(from = 2001, to = 2021, by = 5)), format = '%Y'), date_labels = '%Y') +
  labs(title = '슬로프 그래프', x = '연도', y = '입학생수(천명)')

```

# 세그먼트 라인 그래프

```{r}
df_입학자 |> filter(지역 == '전체') |>
  ggplot(aes(x = 석사, y = 박사)) + 
  ggrepel::geom_text_repel(aes(label = 연도)) +
  geom_segment(aes(
                    xend=c(tail(석사, n=-1), NA), 
                    yend=c(tail(박사, n=-1), NA)
                  ),
                  arrow=arrow(length=unit(0.3,"cm"))
      ) + 
  scale_x_continuous(labels = scales::comma) + 
  scale_y_continuous(labels = scales::comma) +
  labs(title = '석사 및 박사 졸업생 변화', x = '석사 졸업생', y = '박사 졸업생')

```


# 덤벨 그래프

```{r}
df_입학자_long |> filter(지역 == '전체', lubridate::year(연도) %in% c(2016, 2021)) |>
  mutate(연도 = lubridate::year(연도)) |>
  select(1, 3, 4) |>
  pivot_wider(names_from = 연도, values_from = 입학생수) |>
  ggplot() +
  geom_point(data = df_입학자_long |> filter(지역 == '전체', 
                                            lubridate::year(연도) %in% c(2016, 2021)) |>
               mutate(연도 = as.character(lubridate::year(연도))) |>
               select(1, 3, 4),
             aes(x = 입학생수, y = 학교종류, color = 연도)) +
  ggalt::geom_dumbbell(aes(x = `2016`, xend = `2021`, y = 학교종류), colour_x="skyblue", colour_xend = 'darkblue', size_x = 2, size_xend = 2) + 
  scale_x_continuous(label=scales::comma) + 
  scale_color_manual(values = c('2016' = 'skyblue', '2021' = 'darkblue')) +
  labs(x=NULL, y=NULL, title="덤벨 그래프")

```


