---
title : 분포(Distribution)의 시각화
output:
  officedown::rdocx_document:
    reference_docx: bookdown.docx
    plots:
      style: Normal
      align: center
      fig.lp: 'fig:'
      topcaption: false
      caption:
        style: Image Caption
        pre: 'Figure '
        sep: ': '
        tnd: 0
        tns: '-'
        fp_text: !expr officer::fp_text_lite(bold = TRUE)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, out.width = '100%', dpi = 120, fig.width = 6.5)

library(showtext)
showtext_auto()
library(tidyverse)
library(readxl)
library(scales)
library(patchwork)

df_입학자 <- read_excel('c:/R/git/datavisualization/chap3/2021_연도별 입학자수.xlsx', 
                 ## 'data' 시트의 데이터를 불러오는데,
                 sheet = 'Sheet0',
                 ## 앞의 10행을 제외하고
                 skip = 3, 
                 ## 첫번째 행은 열 이름을 설정
                 col_names = FALSE, 
                 ## 열의 타입을 설정, 처음 8개는 문자형으로 다음 56개는 수치형으로 설정
                 col_types = c(rep('text', 2), rep('numeric', 30)))
df_입학자 <- df_입학자 |> select(1, 2, 5, 7, 9, 11, 13, 19, 29, 31)

## df_입학자의 열이름을 적절한 이름으로 설정
colnames(df_입학자) <- c('연도', '지역', '전문대학', '교육대학', '일반대학', '방송통신대학', '산업대학', '원격및사이버대학', '석사', '박사')

df_입학자 <- df_입학자 |> filter(!is.na(지역))

df_입학자_long <- df_입학자 |> pivot_longer(3:10, names_to = '학교종류', values_to = '입학생수')


```

```{r include=FALSE}

df_취업통계 <- read_excel('c:/R/git/datavisualization/chap3/2020년 학과별 고등교육기관 취업통계.xlsx', 
                     ## '학과별' 시트의 데이터를 불러오는데,
                     sheet = '학과별',
                     ## 앞의 13행을 제외하고
                     skip = 13, 
                     ## 첫번째 행은 열 이름으로 설정
                     col_names = TRUE, 
                     ## 열의 타입을 설정, 처음 9개는 문자형으로 다음 79개는 수치형으로 설정
                     col_types = c(rep('text', 9), rep('numeric', 79)))

## df_취업통계에서 첫번째부터 9번째까지의 열과 '계'로 끝나는 열을 선택하여 다시 df_취업통계에 저장
df_취업통계 <- df_취업통계 |> select(1:9, ends_with('계'), '입대자')

## df_취업통계 정보 확인
str(df_취업통계)

set.seed(123)
df_취업통계_sample <- df_취업통계 |> filter(취업률_계 != 100, 졸업자_계 >= 1) |>
  filter(졸업자_계 < 500) |>
  sample_n(2000)

df_취업통계_sample$과정구분 <- fct_relevel(df_취업통계_sample$과정구분, '전문대학과정', '대학과정', '대학원과정')

## 대계열의 순서를 맞추기 위해 과정구분을 팩터로 설정하고 레벨의 순서를 설정
df_취업통계_sample$대계열 <- fct_relevel(df_취업통계_sample$대계열, '인문계열', '사회계열', '교육계열', '자연계열', '공학계열', '의약계열', '예체능계열')

theme_set(theme(
    axis.ticks = element_blank(),
    axis.line = element_line(colour = "grey50"),
    panel.grid = element_line(color = "#b4aea9"),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_line(linetype = "dashed"),
    panel.background = element_rect(fill = "#fbf9f4", color = "#fbf9f4"),
    plot.background = element_rect(fill = "#fbf9f4", color = "#fbf9f4"), 
    legend.background = element_rect(fill = "#fbf9f4", color = "#fbf9f4"), 
    legend.key = element_rect(fill = "#fbf9f4", color = NA)
  ))
```

# 히스토그램

## bin, binwidth

```{r}
p_histo <- df_취업통계 |>
  ggplot(aes(x = 취업률_계))

p_histo +
  geom_histogram()

```

```{r}
p_histo + 
  geom_histogram(aes(y = ..count..))

```

```{r}
p_histo +
  geom_histogram(aes(y = ..count..)) +
  stat_bin(aes(x = 취업률_계,y=..count.., label=..count..), geom="text", vjust=-.5)

```

```{r eval = FALSE}
p_histo +
  geom_histogram(aes(y = ..count..), bins = 20) +
  stat_bin(aes(y=..count.., label=..count..), bins = 20, geom="text", vjust=-.5) +
  labs(title = 'bins = 20')

p_histo +
  geom_histogram(aes(y = ..count..), bins = 30) +
  stat_bin(aes(y=..count.., label=..count..), bins =30, geom="text", vjust=-.5) +
  labs(title = 'bins = 30(default)')

p_histo +
  geom_histogram(aes(y = ..count..), bins = 50) +
  stat_bin(aes(y=..count.., label=..count..), bins = 50, geom="text", vjust=-.5) +
  labs(title = 'bins = 50')

p_histo +
  geom_histogram(aes(y = ..count..), bins = 100) +
  stat_bin(aes(y=..count.., label=..count..), bins = 100, geom="text", vjust=-.5) +
  labs(title = 'bins = 100')

```

```{r echo = FALSE}
((p_histo +
  geom_histogram(aes(y = ..count..), bins = 20) +
  stat_bin(aes(y=..count.., label=..count..), bins = 20, geom="text", vjust=-.5, size = 2) +
  labs(title = 'bins = 20')) +
(p_histo +
  geom_histogram(aes(y = ..count..), bins = 30) +
  stat_bin(aes(y=..count.., label=..count..), bins =30, geom="text", vjust=-.5, size = 2) +
  labs(title = 'bins = 30(default)')))/
((p_histo +
  geom_histogram(aes(y = ..count..), bins = 50) +
  stat_bin(aes(y=..count.., label=..count..), bins = 50, geom="text", vjust=-.5, size = 2) +
  labs(title = 'bins = 50')) +
(p_histo +
  geom_histogram(aes(y = ..count..), bins = 100) +
  stat_bin(aes(y=..count.., label=..count..), bins = 100, geom="text", vjust=-.5, size = 2) +
  labs(title = 'bins = 100')))

```

```{r eval = FALSE}
p_histo +
  geom_histogram(aes(y = ..count..), binwidth = 25) +
  stat_bin(aes(y=..count.., label=..count..), binwidth = 25, geom="text", vjust=-.5) +
  labs(title = 'binwidth = 25')

p_histo +
  geom_histogram(aes(y = ..count..), binwidth = 20) +
  stat_bin(aes(y=..count.., label=..count..), binwidth = 20, geom="text", vjust=-.5) +
  labs(title = 'binwidth = 20')

p_histo +
  geom_histogram(aes(y = ..count..), binwidth = 10) +
  stat_bin(aes(y=..count.., label=..count..), binwidth = 10, geom="text", vjust=-.5) +
  labs(title = 'binwidth = 10')

p_histo +
  geom_histogram(aes(y = ..count..), binwidth = 5) +
  stat_bin(aes(y=..count.., label=..count..), binwidth = 5, geom="text", vjust=-.5) +
  labs(title = 'binwidth = 5')

```

```{r echo = FALSE}
((p_histo +
  geom_histogram(aes(y = ..count..), binwidth = 25) +
  stat_bin(aes(y=..count.., label=..count..), binwidth = 25, geom="text", size = 2, vjust=-.5) +
  labs(title = 'binwidth = 25')) +

(p_histo +
  geom_histogram(aes(y = ..count..), binwidth = 20) +
  stat_bin(aes(y=..count.., label=..count..), binwidth = 20, geom="text", size = 2, vjust=-.5) +
  labs(title = 'binwidth = 20'))) /

((p_histo +
  geom_histogram(aes(y = ..count..), binwidth = 10) +
  stat_bin(aes(y=..count.., label=..count..), binwidth = 10, geom="text", size = 2, vjust=-.5) +
  labs(title = 'binwidth = 10')) +

(p_histo +
  geom_histogram(aes(y = ..count..), binwidth = 5) +
  stat_bin(aes(y=..count.., label=..count..), binwidth = 5, geom="text", size = 2, vjust=-.5) +
  labs(title = 'binwidth = 5')))
```


## bin 분할 원리

```{r}
p_histo2_1 <- p_histo +
  geom_histogram(aes(y = ..count..), bins = 3) +
  stat_bin(aes(y=..count.., label=..count..), bins = 3, geom="text", vjust=-.5)

p_histo2_1
```

```{r}
range.x <- max(df_취업통계$취업률_계) - min(df_취업통계$취업률_계)

p_histo2_1 + 
  geom_vline(aes(xintercept = range.x/2), color = 'red', linetype = 2)

```

```{r}
p_histo2_1 + 
  geom_vline(aes(xintercept = range.x/2), color = 'red', linetype = 2) + 
  geom_vline(xintercept = range.x/2, color = 'red') + ## X축의 1/2 위치
  geom_vline(xintercept = range.x/2/2, color = 'red') + ## X축의 1/4 위치 
  geom_vline(xintercept = range.x/2/2*3, color = 'red') + ## X축의 3/4 위치
  scale_x_continuous(breaks = c(min(df_취업통계$취업률_계), 
                                range.x/2/2, 
                                range.x/2,
                                range.x/2/2*3,
                                max(df_취업통계$취업률_계)
                                )
  )

```


```{r}
p_histo2_1 + 
  geom_vline(xintercept = 50, color = 'yellow', linetype = 2) + 
  geom_vline(xintercept = 0, color = 'yellow', linetype = 2) + 
  geom_vline(xintercept = 100, color = 'yellow', linetype = 2) + 
  geom_vline(xintercept = 25, color = 'red') + ## X축의 1/4 위치 
  geom_vline(xintercept = 75, color = 'red') + ## X축의 3/4 위치
  scale_x_continuous(breaks = c(min(df_취업통계$취업률_계), 
                                range.x/2/2, 
                                range.x/2,
                                range.x/2/2*3,
                                max(df_취업통계$취업률_계)
                                )
  )

```

```{r eval = FALSE}
p_histo +
  geom_bar() +
  scale_x_binned(n.breaks = 3, right = T) +
  labs(title = 'n.breaks = 3')

p_histo +
  geom_bar() +
  scale_x_binned(n.breaks = 5, right = T) +
  labs(title = 'n.breaks = 5')

p_histo +
  geom_bar() +
  scale_x_binned(n.breaks = 10, right = T) +
  labs(title = 'n.breaks = 10')

p_histo +
  geom_bar() +
  scale_x_binned(n.breaks = 20, right = T) +
  labs(title = 'n.breaks = 20')

```

```{r echo = FALSE}
(p_histo +
  geom_bar() +
  scale_x_binned(n.breaks = 3, right = T) +
  labs(title = 'n.breaks = 3') +

p_histo +
  geom_bar() +
  scale_x_binned(n.breaks = 5, right = T) +
  labs(title = 'n.breaks = 5')) /

(p_histo +
  geom_bar() +
  scale_x_binned(n.breaks = 10, right = T) +
  labs(title = 'n.breaks = 10') +

p_histo +
  geom_bar() +
  scale_x_binned(n.breaks = 20, right = T) +
  labs(title = 'n.breaks = 20'))

```

## 히스토그램의 축 변환


```{r}
p_histo3 <- df_취업통계 |> filter(졸업자_계 < 500) |>
  ggplot()

p_histo3_1 <- p_histo3 +
  geom_histogram(aes(x = 졸업자_계), bins = 50)

p_histo3_1
```

```{r eval = FALSE}
p_histo3_1 +
  scale_x_log10() +
  labs(title = 'log10 변환')

p_histo3_1 +
  scale_x_sqrt() +
  labs(title = 'sqrt 변환')

```

```{r echo = FALSE}
(p_histo3_1 +
  scale_x_log10() +
  labs(title = 'log10 변환')) /
(p_histo3_1 +
  scale_x_sqrt() +
  labs(title = 'sqrt 변환'))

```


## 사용자 정의 히스토그램


```{r}
df_취업통계$취업률_그룹 <- cut(df_취업통계$취업률_계, breaks = 10, label = paste0(1:10, '그룹'))

df_취업통계 |>
  ggplot() +
  geom_bar(aes(x = 취업률_그룹, y = ..count..))
```

```{r}
df_취업통계$취업률_그룹 <- cut(df_취업통계$취업률_계, breaks = c(-Inf, 30, 40, 50, 60, 70, 80, 90, 100), label = c('30% 이하', '40%대', '50%대', '60%대', '70%대', '80%대', '90%대', '100%'))

df_취업통계 |>
  ggplot() +
  geom_bar(aes(x = 취업률_그룹, y = ..count..))

```

```{r}
df_취업통계 |>
  mutate(취업률_그룹 = case_when(
    취업률_계 < 30 ~ '30%이하', 
    취업률_계 >= 30 & 취업률_계 < 40 ~ '30%대', 
    취업률_계 >= 40 & 취업률_계 < 50 ~ '40%대', 
    취업률_계 >= 50 & 취업률_계 < 60 ~ '50%대', 
    취업률_계 >= 60 & 취업률_계 < 70 ~ '60%대', 
    취업률_계 >= 70 & 취업률_계 < 80 ~ '70%대', 
    취업률_계 >= 80 & 취업률_계 < 90 ~ '80%대', 
    취업률_계 >= 90 & 취업률_계 < 100 ~ '90%대',
    TRUE ~ '100%'
  ))

df_취업통계 |>
  ggplot() +
  geom_bar(aes(x = 취업률_그룹, y = ..count..))

```

```{r}
df_취업통계$취업률_그룹 <- case_when( 
    df_취업통계$취업률_계 < 30 ~ '30%이하', 
    df_취업통계$취업률_계 >= 30 & df_취업통계$취업률_계 < 40 ~ '30%대', 
    df_취업통계$취업률_계 >= 40 & df_취업통계$취업률_계 < 50 ~ '40%대', 
    df_취업통계$취업률_계 >= 50 & df_취업통계$취업률_계 < 60 ~ '50%대', 
    df_취업통계$취업률_계 >= 60 & df_취업통계$취업률_계 < 70 ~ '60%대', 
    df_취업통계$취업률_계 >= 70 & df_취업통계$취업률_계 < 80 ~ '70%대', 
    df_취업통계$취업률_계 >= 80 & df_취업통계$취업률_계 < 90 ~ '80%대', 
    df_취업통계$취업률_계 >= 90 & df_취업통계$취업률_계 < 100 ~ '90%대',
    TRUE ~ '100%'
  )

df_취업통계 |>
  ggplot() +
  geom_bar(aes(x = 취업률_그룹, y = ..count..))


```

# 밀도 분포 그래프

## 다중 밀도 분포 그래프

```{r}
p_density <- df_취업통계 |> filter(취업률_계 != 100, 취업률_계 != 0) |>
  ggplot()

p_density +
  geom_density(aes(x = 취업률_계, color = 과정구분, fill = 과정구분, linetype = 과정구분), alpha=0.4, position = 'identity') + 
  facet_wrap(~대계열)

```


## ridge 그래프

```{r}
if(!require('ggridges')) {
  install.packages('ggridges')
  library(ggridges)
}

p_density +
 geom_density_ridges(aes(x = 취업률_계, y = 대계열, fill = 과정구분), alpha=0.4, position = 'identity')


```
## marginal

```{r}
if(!require('ggExtra')) {
  install.packages('ggExtra')
  library(ggExtra)
}

p_marginal <- df_취업통계_sample |> filter(취업률_계 != 100, 졸업자_계 >= 1) |>
  ggplot() +
  geom_point(aes(x = 졸업자_계, y = 취업자_합계_계))


  ggMarginal(p_marginal, df_취업통계_sample, x = 졸업자_계, y = 취업자_합계_계, type = 'histogram')

```

# 박스 플롯과 바이올린 플롯

## 기본 플롯

```{r}

p_boxplot <- df_취업통계_sample |>
  ggplot() + 
  labs(title = '박스 플롯', x = '대계열', y = '취업률')

p_boxplot +
  geom_boxplot(aes(x = 대계열, y = 취업률_계))

```

## 평균값 표현

```{r}
df_취업통계_sample |>
  ggplot() + 
  labs(title = '박스 플롯', x = '대계열', y = '취업률') +
  geom_boxplot(aes(x = 대계열, y = 취업률_계)) +
  geom_point(aes(x = 대계열, y = 취업률_계), stat = 'summary', fun.y = 'mean', color = 'tomato3', shape = 4) + 
  geom_text(aes(x = 대계열, y = 취업률_계, label = round(..y.., 1)), stat = 'summary', fun.y = 'mean', color = 'tomato3', vjust = 1.5)

```


## highlight boxplot

```{r}
df_취업통계_sample$highlight <- ifelse(df_취업통계_sample$대계열 == '자연계열', 1, 0)

p_boxplot <- df_취업통계_sample |>
  ggplot() + 
  labs(title = '박스 플롯', x = '대계열', y = '취업률')

p_boxplot +
  geom_boxplot(aes(x = 대계열, y = 취업률_계, fill = as.factor(highlight)), show.legend = FALSE) +
  geom_point(aes(x = 대계열, y = 취업률_계), stat = 'summary', fun.y = 'mean', color = 'tomato3', shape = 4) + 
  geom_text(aes(x = 대계열, y = 취업률_계, label = round(..y.., 1)), stat = 'summary', fun.y = 'mean', color = 'tomato3', vjust = 1.5) +
  scale_fill_manual(values=c("grey", "dodgerblue1")) 

```

## grouped boxplot

```{r}
p_boxplot +
  geom_boxplot(aes(x = 대계열, y = 취업률_계, fill = 과정구분))

```

## facet boxplot

```{r}
p_boxplot +
  geom_boxplot(aes(x = 대계열, y = 취업률_계, fill = as.factor(highlight)), show.legend = FALSE) +
  facet_wrap(~과정구분) + 
  theme(axis.text.x = element_text(angle = -45, vjust = 0.5)) +
  scale_fill_manual(values=c("grey", "dodgerblue1")) 


```

## boxplot with jitter

```{r}
p_boxplot +
  geom_boxplot(aes(x = 대계열, y = 취업률_계)) +
  geom_jitter(aes(x = 대계열, y = 취업률_계), alpha = 0.2, color = 'orange') +
  geom_point(aes(x = 대계열, y = 취업률_계), stat = 'summary', fun.y = 'mean', color = 'tomato3', shape = 4) + 
  geom_text(aes(x = 대계열, y = 취업률_계, label = round(..y.., 1)), stat = 'summary', fun.y = 'mean', color = 'tomato3', vjust = 1.5)
  
```
## 박스플롯과 바이올린 플롯의 병합

```{r}
p_violin <- df_취업통계_sample |>
  ggplot() + 
  labs(title = '바이올린 플롯', x = '대계열', y = '취업률')
  
p_violin +
  geom_violin(aes(x = 대계열, y = 취업률_계, fill = as.factor(highlight)), show.legend = FALSE) +
  geom_boxplot(aes(x = 대계열, y = 취업률_계), width=0.2, color="white", alpha=0.2) +
  geom_point(aes(x = 대계열, y = 취업률_계), stat = 'summary', fun.y = 'mean', color = 'tomato3', shape = 4) + 
  geom_text(aes(x = 대계열, y = 취업률_계, label = round(..y.., 1)), stat = 'summary', fun.y = 'mean', color = 'tomato3', vjust = 1.5) +
  scale_fill_manual(values=c("grey", "dodgerblue1"))
  
```


# 피라미드 플롯

```{r}
brks <- seq(from = -300000, to = 300000, by = 50000)
lbls <- paste0(as.character(c(seq(300, 0, -50), seq(50, 300, 50))), "K")


df_입학자_pyramid<- df_입학자_long |>
  filter(학교종류 %in% c('전문대학', '일반대학'), 지역 == '전체') |>
  mutate(입학생수 = ifelse(학교종류 == '전문대학', 입학생수 * -1, 입학생수))


p_pyramid <- df_입학자_pyramid |>
  ggplot() + 
  labs(title = '일반대, 전문대 입학생수 변화')


p_pyramid +
  geom_col(aes(x = 연도, y = 입학생수, fill = 학교종류)) + 
  scale_y_continuous(breaks = brks, labels = lbls) +
  scale_x_discrete(limits=rev) + 
  coord_flip() + 
  scale_fill_brewer(palette = "Dark2")  # Color palette

```

